
com.example.emp-id=1
com.example.id-details.panNumber=bydp4567
com.example.name=Manohar
com.example.nick-name=manu
com.example.phone-no[0]=7386190624
com.example.team-members[0]=rahul
com.example.team-members[1]=vishal

com.example.size=200
com.example.company-name=hcl
com.example.location=hyd



